### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by Axeinator** [ruwix/powerschool-api#3]
I would like to use this in an Flask project I am working on, it basically consists of fetching and adding simulated assignments to calculate required scores. If this is possible, please add a License, such as the MIT License, the GNU GPLv3, or the Apache 2.0.

**Comment by grantpauker** [comment]
I added an MIT License. I made this over 2 years ago so there is no guarantee that it will still work. I believe powerschool has an actual api you can use as seen in [this](https://github.com/reteps/gopowerschool) repo if you want to check that out.
